### ISSUE TITLE
Stream error occours when lauching a new job

### ISSUE THREAD

**Issue by jarvenshan** [WeBankFinTech/eggroll#156]
**Describe the bug**
Stream error occours when lauching a new job in fate

**What version of Eggroll and what programming language (including its version) are you using?**
0.3,python

**What is the severance of this issue and why? **
L0 : the training job got stuck and cannot solve it by rebooting.

**How to reproduce this issue?**
1. Lauch a new training job in fate(and stuck)
2. go to roll/logs/error.log
3. See 'Stream error'

**What did you expect to see?**
Should be all good with no errors

**What did you see instead?**
Stream error

**Could you offer us the error logs or error screenshot?**
If applicable, add logs or screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/35085507/70601464-08810280-1c2d-11ea-8cfb-1ce25be0288a.png)

**What is your environment information (please complete the following information)?**
 - OS: [windows]
 - Version [10]

**Anything else we should know about your project / environment?**

**Comment by drougon** [comment]
fixed in v2.0
