### ISSUE TITLE
roll report connection refuse when lauching a new job

### ISSUE THREAD

**Issue by jarvenshan** [WeBankFinTech/eggroll#261]
**Describe the bug**
roll report connection refuse when lauching a new job

**What version of Eggroll and what programming language (including its version) are you using?**
python.Eggroll 0.3

**What is the severance of this issue and why? **
L1 - System totally unavailable; 
the training job got stuck and cannot solve it by rebooting.

**How to reproduce this issue?**
1.Lauch a new training job in fate(and stuck)
2.go to roll/logs/fate-roll.log
3.See 'connection refuse'

**What did you expect to see?**
should not be an error

**What did you see instead?**
connection refuse

**Could you offer us the error logs or error screenshot?**
![image](https://user-images.githubusercontent.com/35085507/72604753-7e783800-3956-11ea-98b2-7ba6f426cfb3.png)

**What is your environment information (please complete the following information)?**
 - OS: [win10]

**Comment by drougon** [comment]
fixed in v2.0
