### ISSUE TITLE
建表sql在mariadb中无法使用

### ISSUE THREAD

**Issue by mask-pp** [WeBankFinTech/eggroll#479]
https://github.com/mask-pp/eggroll/blob/0a8dc94894d9d87cd4ac4feb78f6868c0822fcf3/jvm/core/main/resources/create-eggroll-meta-tables.sql#L83，主键用这么大的字段，这种用法不合适吧？使用了DATATIME 字段后在mariadb中无法使用，是不是拿了sqlite建表语句没做任何修改？

**Comment by mask-pp** [comment]
和h2建表语句相同，希望能把这方面问题修复一下

**Comment by maxwong** [comment]
Translate:
https://github.com/mask-pp/eggroll/blob/0a8dc94894d9d87cd4ac4feb78f6868c0822fcf3/jvm/core/main/resources/create-eggroll-meta-tables.sql#L83

Isn't it inappropriate to use such a long field for primary key? DATETIME field cannot be used in mariadb. Did you copy the create table statements in sqlite and did not make any change?

(The create table statements) are the same with h2. Hope you can fix these issues.

**Comment by maxwong** [comment]
@mask-pp Sorry for the inconvenience. But we've tested the statements in mysql 5.7+ and it is working well online.
But we do notice that the create table statements are not working in some databases (e.g. mariadb and tdsql). There are 2 possible issues:

1. These databases do not support long primary keys (typical length is 767 bytes).
2. These databases require an explicit primary key for every table.

We have made changes and they will be released in v2.2.1 (eta mid Dec 2020).

For the time being, if you are not using a long session id, please feel free to shorten the key size to 760.

Sorry again for the inconveniences.
