### ISSUE TITLE
remote procedure call and fault-tolerance

### ISSUE THREAD

**Issue by ssdyue** [WeBankFinTech/eggroll#483]
Does Eggroll supports remote procedure call ?  And is there a fault-tolerance mechanism? 
If so, is a Python or Java interface available to use?
If not, will you join the plan in the future?

**Comment by maxwong** [comment]
Hi ssdyue. Thanks for the question.
Eggroll is implemented with gRPC which is remote procedure call.
We have a few fault tolerance mechanism. Could you describe your scenario in more detail? In that way we can provide a more detailed answer for your usage.

**Comment by ssdyue** [comment]
Hi, @maxwong, Thanks for your answer, the following is a detailed description of my problems.
On the first question, suppose there is such a scenario: There are two machines A and B, and machine A has the eggroll, but machine  B doesn't. Can Machine B remotely call machine A's Eggroll service?
On the second question, consider the following scenario: the Guest platform is a cluster with three or more nodes, and if one or more nodes fail, will the whole cluster continue to run normally?
In addition, assuming that the number of CPU cores (cpu cores) is c, the number of Nodemanagers is n, and the number of tasks that need to run simultaneously is p, eggroll.session.processors.per.node is e, then: p = c * 0.8 / e (official documents). So in this case, it doesn't seem to indicate the impact of data size.
I look forward to your reply.

**Comment by maxwong** [comment]
A1: Yes.
A2: This feature is under development and planned in v2.4, ETA early 2021.

A-addition: The purpose of this formula is providing a guidance of how to set the partition number to properly use physical resources, specifically CPU resources. 
If users follow this formula, CPU resources will not be exhausted or crazily performing context switches even the tasks are CPU-intensive. So the data size is indeed irrelevant in this scenario. When the number of CPU cores is fixed, bigger data size requires longer time to compute.

**Comment by ssdyue** [comment]
Thank you very much. It solved my confusion.

**Comment by maxwong** [comment]
Welcome. Closing the issue as problems are solved.
