### ISSUE TITLE
Rollsite support http and https?

### ISSUE THREAD

**Issue by jarviszeng-zjc** [WeBankFinTech/eggroll#532]
GRPC/HTTP2 and TCP are difficult to support on some of the more traditional enterprise network devices

**Comment by maxwong** [comment]
We are working on a solution and please stay tuned.

**Comment by dylan-fan** [comment]
Can this feature be released in October? A banking scenario needs to be used

**Comment by MiKKiYang** [comment]
@maxwong 你好，我目前的项目是基于fate去开发联邦学习的，我目前的场景需要确保party间通信时可以走基于grpc的tls加密通信，我看rollsite已经有支持tls的配置，同时我已经配置好并重新启动了rollsite，然后查看rollsite进程，安全端口和非安全端口都启动了，但是基于tls的grpc通信后，多个party之间的通信失败了，报错时：
`[ERROR] [2021-09-26 02:47:17,122] [10:140527999624960] - api_utils.py[line:47]: ('create job failed', {'host': {10000: {'retcode': <RetCode.FEDERATED_ERROR: 104>, 'retmsg': 'Federated schedule error, Please check if the fate flow server of the other party is started. rpc request error: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "Connection reset by peer"\n\tdebug_error_string = "{"created":"@1632624436.519577492","description":"Error received from peer ipv4:192.167.0.4:9382","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Connection reset by peer","grpc_status":14}"\n>'}}, 'arbiter': {10002: {'retcode': <RetCode.FEDERATED_ERROR: 104>, 'retmsg': 'Federated schedule error, Please check if the fate flow server of the other party is started. rpc request error: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "Connection reset by peer"\n\tdebug_error_string = "{"created":"@1632624436.628106122","description":"Error received from peer ipv4:192.167.0.4:9382","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Connection reset by peer","grpc_status":14}"\n>'}}, 'guest': {10001: {'retcode': <RetCode.FEDERATED_ERROR: 104>, 'retmsg': 'Federated schedule error, Please check if the fate flow server of the other party is started. rpc request error: <_Rendezvous of RPC that terminated with:\n\tstatus = StatusCode.UNAVAILABLE\n\tdetails = "Connection reset by peer"\n\tdebug_error_string = "{"created":"@1632624436.743772567","description":"Error received from peer ipv4:192.167.0.4:9382","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Connection reset by peer","grpc_status":14}"\n>'}}})`

求助，希望能给我讲述下该如何配置两端party的配置，才能让两个party走tls通道，通信成功，感谢

**Comment by maxwong** [comment]
https://github.com/WeBankFinTech/eggroll/wiki/RollSite:-Passing-Through-a-HTTP-1-Network

closing this thread as solution is given.
